import React from 'react'
import Head from 'next/head'
import Home from '../components/Home/Home'
import Layout from '../components/Layout/Layout'

export default function Index() {
  return (
    <div>
      <Head>
        <title>Shop</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main>
        <Layout>
          <Home />
        </Layout>
      </main>
    </div>
  )
}
